# Generated by Django 5.0.7 on 2024-07-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuário'},
        ),
    ]
